# Generated by Django 5.0.4 on 2024-04-20 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_course_coursesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.coursesection'),
            preserve_default=False,
        ),
    ]
