# Generated by Django 5.0.4 on 2024-04-20 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.course'),
        ),
    ]
